# 0.9236 Private
# 0.9240 Public
ensemble:
  tta: d4
  tta_mode: model
  models:
    - https://github.com/BloodAxe/DrivenData-2021-Geopose-Solution/releases/download/1.0/210709_07_54_b7_unet_fold0_best.pth
    - https://github.com/BloodAxe/DrivenData-2021-Geopose-Solution/releases/download/1.0/210714_15_13_b6_rdtsc_unet_fold9_train.88.pth

inference:
  batch_size: 1
  num_workers: 4
  fp16: True

submission_dir: submissions/b6_rdtsc_unet_fold9_b7_unet_fold0_d4_bo1
